deployment:
  tasks:
    - export DEPLOYPATH=/home/kina3126/public_html/absen.kanpa.co.id
    - /bin/cp -R application $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R upload $DEPLOYPATH
    - /bin/cp .gitignore $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp composer.lock $DEPLOYPATH
    - /bin/cp license.txt $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
